apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbd
---
apiVersion: v1
kind: Pod
metadata:
  name: ubi8-pod
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: ubi8-container
    resources:
      limits:
        cpu: 1
        memory: 512Mi
      requests:
        memory: 512Mi
    securityContext:
      capabilities:
        drop:
          - ALL
      runAsNonRoot: true
      allowPrivilegeEscalation: false

    image: registry.access.redhat.com/ubi8/ubi
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - mountPath: /mnt/storage
      name: storage
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: my-pvc