apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpine-app
  template:
    metadata:
      labels:
        app: alpine-app
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
      - name: alpine-container
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            memory: 512Mi

        image: alpine:latest
        command: ["sh", "-c", "while true; do sleep 3600; done"]
        securityContext:
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          allowPrivilegeEscalation: false

