apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: udn-2-primary 
  namespace: udn1-ns
spec:
  topology: Layer3 
  layer3: 
    role: Primary 
    subnets: 
      - cidr: 192.168.0.0/16
        hostSubnet: 24
      - cidr: 2001:db8::/60
        hostSubnet: 64