apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: aws-metal-us-east-2b
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: cluster-tcs7t-bczvq
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: cluster-tcs7t-bczvq
      machine.openshift.io/cluster-api-machineset: aws-metal-us-east-2b
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: cluster-tcs7t-bczvq
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: aws-metal-us-east-2b
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          userDataSecret:
            name: worker-user-data
          placement:
            availabilityZone: us-east-2b
            region: us-east-2
          credentialsSecret:
            name: aws-cloud-credentials
          instanceType: m5zn.metal
          metadata:
            creationTimestamp: null
          blockDevices:
            - ebs:
                encrypted: true
                iops: 0
                kmsKey:
                  arn: ''
                volumeSize: 250
                volumeType: gp3
          securityGroups:
            - filters:
                - name: 'tag:Name'
                  values:
                    - cluster-tcs7t-bczvq-node
            - filters:
                - name: 'tag:Name'
                  values:
                    - cluster-tcs7t-bczvq-lb
          kind: AWSMachineProviderConfig
          metadataServiceOptions: {}
          tags:
            - name: kubernetes.io/cluster/cluster-tcs7t-bczvq
              value: owned
            - name: Stack
              value: project ocp4-cluster-tcs7t
            - name: env_type
              value: ocp4-cluster
            - name: guid
              value: tcs7t
            - name: owner
              value: unknown
            - name: platform
              value: RHPDS
            - name: uuid
              value: 95ee014d-d426-58fd-845f-7a4fc52ebda7
          deviceIndex: 0
          ami:
            id: ami-08bb6907b96d2a024
          subnet:
            filters:
              - name: 'tag:Name'
                values:
                  - cluster-tcs7t-bczvq-subnet-private-us-east-2b
          apiVersion: machine.openshift.io/v1beta1
          iamInstanceProfile:
            id: cluster-tcs7t-bczvq-worker-profile
