apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br-vmdata
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: ''  # set nodeSelector to the desired node(s).
                                        # it's recommended to test applying to one node for testing
                                        # kubernetes.io/hostname: <hostname>
  desiredState:
    interfaces:
      - name: br-vmdata
        type: ovs-bridge
        state: up
        bridge:
          allow-extra-patch-ports: true
          options:
            stp: false
          port:
            - name: bond0
    ovn:
      bridge-mappings:
        - localnet: vmdata      # logical name, used un NADs
          bridge: br-vmdata     # name of the bridge
          state: present